-- HRMS V2 Performance Indexing Patch
-- Target: Sub-300ms reporting response times
-- Generated by Antigravity (Noah Logic Audit Follow-up)

-- 1. Optimize Attendance Reporting
CREATE INDEX idx_attendance_emp_date ON attendance_logs (employee_id, attendance_date);

-- 2. Optimize Leave Management filtering
CREATE INDEX idx_leave_emp_status ON leave_requests (employee_id, status);

-- 3. Optimize Appraisal Cycle lookups
CREATE INDEX idx_appraisal_cycle_status ON employee_appraisals (cycle_id, status);

-- 4. General Performance improvements for JOINS
CREATE INDEX idx_employees_dept ON employees (department_id);
CREATE INDEX idx_employees_desig ON employees (designation_id);
CREATE INDEX idx_employees_manager ON employees (reporting_manager_id);
